version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_dashboard
    environment:
      POSTGRES_DB: dashboardfinancial_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 90sdearcade
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d dashboardfinancial_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  backend:
    image: xtsulyts/django_docker_dashboard_financial_backend:latest
    container_name: django_backend
    ports:
      - "8000:8000"
    environment:
      DB_ENGINE: django.db.backends.postgresql
      DB_NAME: dashboardfinancial_db
      DB_USER: postgres
      DB_PASSWORD: 90sdearcade
      DB_HOST: db
      SECRET_KEY: "django-insecure-7@-w=*(z&$hx@(^$u=9l%#kcmt8r60f4zcl4#_9czye5(xjw)h"
      DB_PORT: 5432
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    # COMANDO CORREGIDO - Una sola línea ejecutable
    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "

  frontend:
    image: xtsulyts/nextjs_docker_dashboard_financial_frontend:latest # Usa tu imagen de Docker Hub
    container_name: nextjs_frontend
    ports:
      - "3000:3000"
    environment:
      API_URL: http://backend:8000
      NEXT_PUBLIC_API_URL: http://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data: