# Generated by Django 5.1.6 on 2026-04-13 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='fuente',
            field=models.CharField(choices=[('manual', 'Manual'), ('mercadopago', 'MercadoPago')], default='manual', max_length=20, verbose_name='Fuente'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='mp_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID de pago MercadoPago'),
        ),
    ]
