# Generated by Django 5.1.6 on 2026-04-13 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_transaccion_fuente_transaccion_mp_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='mp_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='mp_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
